# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ba2e723ab43c8f0e747d20b09ac550063577391d6c9f0da1627b48dda3e5fb40f3f2dde49b031ffa19132081cbe745f1522db672572c7caae643bf57a5edfc4

test:
  secret_key_base: d31ad24a7e2857d98487f808d5a421f6ae87fbbea6d9da16ae39c051af87a0eca7dea030f851c00da2a32c1d9df90deb26fd5dc95ac6d0164f1f91a5425bfdb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
